version: '3.5'

volumes:
  trustanchors:
  storage:
  gridmapdir:

networks:
  test.example:
    name: test.example

services:

  trust:
    container_name: trust
    image: indigoiam/trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates

  testsuite:
    image: italiangrid/storm-testsuite:${TESTSUITE_BRANCH}
    container_name: testsuite
    dns_search: test.example
    hostname: testsuite.test.example
    # entrypoint: sleep infinity
    entrypoint: sh /assets/run_testsuite.sh
    environment:
      - TESTSUITE_BRANCH=nightly
      - TESTSUITE_EXCLUDE=to-be-fixedORno-btrfsORcdmi
      - TESTSUITE_SUITE=tests
    depends_on:
      - storm
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./assets/testsuite:/assets
    networks:
      test.example:
        aliases:
          - testsuite.test.example

  storm:
    image: italiangrid/tf-node
    container_name: storm
    dns_search: test.example
    hostname: storm.test.example
    environment:
      - STORM_TARGET_RELEASE
      - VOMS_TARGET_RELEASE
      - PKG_STORM_BRANCH
      - PKG_VOMS_BRANCH
    ports:
      - 8080:8080
      - 9998:9998
      - 2170:2170
      - 8085:8085
      - 8443:8443
      - 8444:8444
    depends_on:
      - trust
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - ./assets/node:/assets/node
      - ./assets/services:/assets/services
      - storage:/storage
      - gridmapdir:/etc/grid-security/gridmapdir
#      - /Users/vianello/eclipse-workspace-2020-06/storm-puppet-module:/storm-puppet-module
#      - /Users/vianello/eclipse-workspace-2020-06/puppet-lcmaps:/puppet-lcmaps
    cap_add:
      - SYS_ADMIN
    privileged: true
    networks:
      test.example:
        aliases:
          - storm.test.example
