pipeline {

  agent {
    label 'deployment-test'
  }

  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '5'))
    disableConcurrentBuilds()
  }

  parameters {
    string(name: 'STORM_TARGET_RELEASE', defaultValue: "stable", description: 'Which StoRM repositories have to be installed/enabled. Values: nightly beta and stable')
    string(name: 'VOMS_TARGET_RELEASE', defaultValue: "stable", description: 'Which VOMS repositories have to be installed/enabled. Values: nightly beta and stable')
    string(name: 'PKG_STORM_BRANCH', defaultValue: "v1.11.22", description: '')
    string(name: 'PKG_STORM_PLATFORM', defaultValue: "centos7java11", description: '')
    string(name: 'PKG_VOMS_BRANCH', defaultValue: "none", description: '')
    string(name: 'PUPPET_MODULE_BRANCH', defaultValue: "puppet7", description: 'storm-puppet-module remote branch')
    string(name: 'UPDATE_FROM_STABLE', defaultValue: "no", description: 'Write yes to first install stable and then update with STORM_TARGET_RELEASE. No means a clean deployment')
  }

  environment {
    TTY_OPTS = "-T"
    STORM_TARGET_RELEASE = "${params.STORM_TARGET_RELEASE}"
    VOMS_TARGET_RELEASE = "${params.VOMS_TARGET_RELEASE}"
    PKG_STORM_BRANCH = "${params.PKG_STORM_BRANCH}"
    PKG_STORM_PLATFORM = "${params.PKG_STORM_PLATFORM}"
    PKG_VOMS_BRANCH = "${params.PKG_VOMS_BRANCH}"
    PUPPET_MODULE_BRANCH = "${params.PUPPET_MODULE_BRANCH}"
    UPDATE_FROM_STABLE = "${params.UPDATE_FROM_STABLE}"
  }

  stages {
    stage('Run') {
      steps {
        script {
          echo "TTY_OPTS=${env.TTY_OPTS}"
          dir("all-in-one/centos7") {
            sh "bash ./run.sh"
          }
        }
      }
    }
  }
  post {
    always {
      archiveArtifacts 'all-in-one/centos7/output/**'
      step([$class: 'RobotPublisher',
        disableArchiveOutput: false,
        logFileName: 'log.html',
        otherFiles: '*.png',
        outputFileName: 'output.xml',
        outputPath: "all-in-one/centos7/output/reports",
        passThreshold: 100,
        reportFileName: 'report.html',
        unstableThreshold: 90])
    }
    failure {
      slackSend channel: '#ci-deployment-tests', color: 'danger', message: "${env.JOB_NAME} - #${env.BUILD_ID} Failure (<${env.BUILD_URL}|Open>)"
    }
    changed {
      script {
        if ('SUCCESS'.equals(currentBuild.result)) {
          slackSend channel: '#ci-deployment-tests', color: 'good', message: "${env.JOB_NAME} - #${env.BUILD_ID} Back to normal (<${env.BUILD_URL}|Open>)"
        }
      }
    }
  }
}
