FROM italiangrid/base:centos6

ADD . /

RUN chmod +x /setup.sh
RUN sh /setup.sh

# expose StoRM ports
EXPOSE 8080 8085 8086 8443 8444 9998 2710

# setup deployment script
RUN chmod +x /deploy.sh

# setup StoRM daemons
RUN chmod -R +x /daemons
