#!/usr/bin/env groovy
pipeline {

  agent { label 'docker' }

  options {
    timeout(time: 1, unit: 'HOURS')
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }

  triggers { cron('@daily') }

  stages {
    stage('prepare') {
      steps {
        deleteDir()
        checkout scm
      }
    }

    stage('build and push tf-node image') {
      steps {
        script {
          dir("docker/tf-node") {
            sh "sh build-image.sh"
            sh "sh push-image.sh"
          }
        }
      }
    }

    stage('build and push systemd-node image') {
      steps {
        script {
          dir("docker/systemd-node") {
            sh "sh build-image.sh"
            sh "sh push-image.sh"
          }
        }
      }
    }
  }

  post {
    failure {
      slackSend color: 'danger', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Failure (<${env.BUILD_URL}|Open>)"
    }

    changed {
      script {
        if ('SUCCESS'.equals(currentBuild.currentResult)) {
          slackSend color: 'good', message: "${env.JOB_NAME} - #${env.BUILD_NUMBER} Back to normal (<${env.BUILD_URL}|Open>)"
        }
      }
    }
  }
}
