apiVersion: v1
kind: Pod
metadata:
    labels:
        ci-job: storm-deployment-test
spec:
    nodeSelector:
        zone: ci
    imagePullSecrets:
      - name: cloud-vm114
    volumes:
      - name: docker
        hostPath:
            path: /var/run/docker.sock
      - name: registry
        secret:
            secretName: registry-auth-basic
      - name: ssh
        secret:
            secretName: jenkins-ssh-keys
      - name: scratch
        persistentVolumeClaim:
            claimName: scratch-area-claim
    containers:
      - name: kube-docker-runner
        image: cloud-vm114.cloud.cnaf.infn.it/italiangrid/kube-docker-runner:latest
        command:
          - cat
        tty: true
        volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock
          - name: registry
            mountPath: /home/jenkins/.docker
          - name: ssh
            mountPath: /home/jenkins/.ssh
          - name: scratch
            mountPath: /srv/scratch
        resources:
            requests:
                memory: 4Gi
                cpu: 1
            limits:
                memory: 4Gi
                cpu: 1
    restartPolicy: Never
