# This is a basic workflow to help you get started with Actions

name: build storm-node docker image

on:
  schedule:
    - cron: 30 3 * * *
  push:

jobs:
  docker-build-storm-node:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          tags: italiangrid/storm-node:latest
          context: ./docker/storm-node
          file: ./docker/storm-node/Dockerfile
          push: false

      - name: Push docker image
        run: docker push italiangrid/storm-node:latest